# Understanding Einstein Summation Notation in NumPy

## Basic Concept
With `einsum`, you:
1. Define labels for each axis of your tensors
2. Specify which labels appear in the output
3. Repeated labels indicate summation along those axes

### Dot Product

In [17]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Regular method
dot_product_regular = np.dot(v1, v2)
print("Dot product using np.dot():", dot_product_regular)

# Using einsum: repeated index 'i' means sum over this dimension
dot_product_einsum = np.einsum('i,i->', v1, v2)
print("Dot product using einsum:", dot_product_einsum)

Dot product using np.dot(): 32
Dot product using einsum: 32


### Outer Product

In [18]:
# Regular method
outer_product_regular = np.outer(v1, v2)
print("Outer product using np.outer():\n", outer_product_regular)

# Using einsum: separate indices 'i,j' with no summation
outer_product_einsum = np.einsum('i,j->ij', v1, v2)
print("Outer product using einsum:\n", outer_product_einsum)

Outer product using np.outer():
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Outer product using einsum:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [19]:
### Matrix-Vector Multiplication
A = np.array([[4, 5], [6, 7]])
v = np.array([4, 5])

# Regular method
mv_regular = A @ v  # or np.matmul(A, v)
print("Matrix-vector product using @:\n", mv_regular)

# Using einsum: sum over the repeated index 'j'
mv_einsum = np.einsum('ij,j->i', A, v)
print("Matrix-vector product using einsum:\n", mv_einsum)

Matrix-vector product using @:
 [41 59]
Matrix-vector product using einsum:
 [41 59]


### Matrix-Matrix Multiplication

In [20]:
A = np.array([[4, 5], [6, 7]])
B = np.array([[3, 4, 5], [6, 8, 1]]).reshape(2, 3)

# Regular method
mm_regular = A @ B  # or np.matmul(A, B)
print("Matrix-matrix product using @:\n", mm_regular)

# Using einsum: sum over the repeated index 'j'
mm_einsum = np.einsum('ij,jk->ik', A, B)
print("Matrix-matrix product using einsum:\n", mm_einsum)

Matrix-matrix product using @:
 [[42 56 25]
 [60 80 37]]
Matrix-matrix product using einsum:
 [[42 56 25]
 [60 80 37]]


### Element-wise Multiplication

In [21]:
A = np.array([[3, 1], [3, 4]])
B = np.array([[4, 5], [1, 2]])

# Regular method
elementwise_regular = A * B
print("Element-wise product using *:\n", elementwise_regular)

# Using einsum: indices remain the same for input and output
elementwise_einsum = np.einsum('ij,ij->ij', A, B)
print("Element-wise product using einsum:\n", elementwise_einsum)

Element-wise product using *:
 [[12  5]
 [ 3  8]]
Element-wise product using einsum:
 [[12  5]
 [ 3  8]]


### Matrix Multiplication Batch-wise

In [22]:

# 3D example
X = np.random.rand(2, 3, 4)  # Shape (2, 3, 4)
Y = np.random.rand(2, 4, 5)  # Shape (2, 4, 5)

# Let's interpret these as:
# X: 2 batches, 3 rows, 4 columns
# Y: 2 batches, 4 rows, 5 columns

# Batch matrix multiplication: brc,bct->brt
# Sum over c (columns of X, rows of Y)
# Free indices: b (batch), r (rows of X), t (columns of Y)
result = np.einsum('brc,bct->brt', X, Y)
print("X shape:", X.shape)
print("Y shape:", Y.shape)
print("Result shape:", result.shape)

X shape: (2, 3, 4)
Y shape: (2, 4, 5)
Result shape: (2, 3, 5)


### Permuting Axes

In [24]:

# Transpose a matrix
A = np.array([[1, 2, 3], [4, 5, 6]])
print("Original A:\n", A)
print("A transpose using .T:\n", A.T)
print("A transpose using einsum:\n", np.einsum('ij->ji', A))

# Permute axes of a 3D tensor
X = np.random.rand(2, 3, 4)
print("Original X shape:", X.shape)
print("Permuted X shape:", np.einsum('ijk->kji', X).shape)  # Should be (4, 3, 2)

Original A:
 [[1 2 3]
 [4 5 6]]
A transpose using .T:
 [[1 4]
 [2 5]
 [3 6]]
A transpose using einsum:
 [[1 4]
 [2 5]
 [3 6]]
Original X shape: (2, 3, 4)
Permuted X shape: (4, 3, 2)
